
<ListGridLayout>:
    BoxLayout:
        orientation: 'vertical'
        id: mainbox
        size_hint_y: None
        size: root.width, root.height
       

        Button:
            text:'add fabric'
            on_press: root.add_instance(box_grid)
        Button:
            text: "add"
            on_press:root.add_quantity()    


        Button:
            text: "res"
            on_press:root.sub_quantity()

        Button:
            text: "close"
            on_press: app.stop()
        
        Button:
            text: 'delete'
            on_press: root.delete_line()

        GridLayout:
            cols:6
            rows:1

            Label:
                text:'name'
            Label: 
                text:'1,40'
            Label:
                text: '1,80'    
            Label:
                text: '2,30'
            Label:
                text:'R 1,40'
            Label:
                text:'R 1,80'

        ScrollView:
            id: main_scroll
            do_scroll_x: False
            do_scroll_y: True
          

            BoxLayout:
                id: box_grid
                orientation: 'vertical'
                size_hint_y: None
                height: self.minimum_height
              

                
            
                

        

        


      

            
        
